name: Docker Image Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      AWS_REGION: us-east-1
      GCP_PROJECT: defang-io
      GCP_REGION: us-central1
      IMAGE_TAG: latest
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for CI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::488659951590:role/ci-role-d4fe904 # ciRoleArn from defang-io/infrastructure stack

      - name: Configure AWS Credentials for Staging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::426819183542:role/admin # adminUserRoleArn from defang-io/bootstrap stack
          role-duration-seconds: 1200
          role-chaining: true

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure GCP Credentials for Shared Services
        uses: "google-github-actions/auth@v2"
        with:
          project_id: ${{ env.GCP_PROJECT}}
          workload_identity_provider: "projects/806289336876/locations/global/workloadIdentityPools/github-actions/providers/github-actions-provider"

      - name: Authenticate to GCR
        run: |
          gcloud auth --project=${GCP_PROJECT} configure-docker ${GCP_REGION}-docker.pkg.dev --quiet

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            RAILPACK_VERSION=0.4.0
          file: Dockerfile
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            defangio/railpack-builder:${{ env.IMAGE_TAG }}
            gcr.io/defang-io/public/railpack-builder:${{ env.IMAGE_TAG }}
            public.ecr.aws/defang-io/codebuild-railpack:${{ env.IMAGE_TAG }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max

      # - name: Push image to public ECR gallery
      #   run: |
      #     docker tag railpack-builder:${IMAGE_TAG} 488659951590.dkr.ecr.us-west-2.amazonaws.com/railpack-builder:${IMAGE_TAG}
      #     docker push 488659951590.dkr.ecr.us-west-2.amazonaws.com/railpack-builder:${IMAGE_TAG}
